# Generated by Django 3.0.7 on 2020-06-07 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_annotations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotations',
            new_name='Annotation',
        ),
    ]
