# Generated by Django 3.0.7 on 2020-06-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200607_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='annotation_images'),
        ),
    ]
