# Generated by Django 3.0.7 on 2020-06-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='annotation_images'),
        ),
    ]
