# Generated by Django 3.0.7 on 2020-06-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200621_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='annotation_images'),
        ),
    ]
