# Generated by Django 3.0.7 on 2020-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200621_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='notes',
            field=models.TextField(max_length=300),
        ),
    ]
