# Generated by Django 3.0.7 on 2020-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200624_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='notes',
            field=models.TextField(max_length=1000),
        ),
    ]
